<?php

/**
 * @file
 * Contains raceresults.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function raceresults_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the raceresults module.
    case 'help.page.raceresults':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Import and access results from races, current and historic') . '</p>';
      return $output;

    default:
  }
}
